services:
  ### DATABASE ###
  database:
    container_name: database
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sacachispa-net

  ### TEST DATABASE ###
  database-test:
    container_name: database-test
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: ${TEST_DATABASE_USER}
      POSTGRES_PASSWORD: ${TEST_DATABASE_PASS}
      POSTGRES_DB: ${TEST_DATABASE_NAME}
    volumes:
      - pgdata-test:/var/lib/postgresql/data
    ports:
      - "${TEST_POSTGRES_PORT}:5432"
    networks:
      - sacachispa-net

  ### API SERVER ###
  apiserver:
    container_name: apiserver
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - "${SERVER_PORT}:8080"

volumes:
  pgdata:
    driver: local
  pgdata-test:
    driver: local

networks:
  sacachispa-net:
    driver: bridge
