services:
  database-ps:
    container_name: ${CONTAINER_NAME}
    image: postgres:12.8
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
